### ISSUE TITLE
Where to start for minion calculator?

### ISSUE THREAD

**Issue by Lennster1** [Lennster1/Hypixel-Skyblock-Utilities#7]
Hey everyone who's contributed to the project, thank so you much. This is really an amazing effort by you guys, and I really appreciate it. OK, now some questions for you guys:

1.  What do you guys think is the best way to store data in a minion calculator? I mean the minion time between actions, items per action, etc; JSON? Python list? Lemme know what you think, then we just plug those variables in the formula. (there's a formula for calculating minion profit)
2. lied about questions, pural

**Comment by outsparkled** [comment]
just put it in a json file since its not that much data

**Comment by Lennster1** [comment]
> just put it in a json file since its not that much data

Yeah, looks like ill do that later sometime
